### PR TITLE
Update package automatically

### PR DESCRIPTION
**Pull request by uiii**
Hi @JipSterk,
your unity-hub package is outdated in chocolatey repository. I'd been trying to contact you via contact form on chocolatey website, but got no response. I've investigated how to update the package automatically. So, I'm posting this PR as a result. It uses Github action and chocolatey's official auto update script. I hope you find it useful and merge it. I also updated the link to Unity hub release notes (was using the wrong one to Unity's release notes). Thanks

### CODE REVIEW

**Comment by uiii** [comment]
There is one requirenemt to set your choco API key, via `CHOCOLATEY_API_KEY` [github secret](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets)

**Comment by uiii** [comment]
Thanks, for merging. I forgot one more thing, to create a commit after the update, maybe it is not necessary, but it would be fine to have the latest version in git as well. Do you want me to add it to actions file?

**Comment by uiii** [comment]
And I see you changed the job schedule. Isn't is too less? One would have to wait a week to get the new version. Yes, every hour is maybe too often, but at least once a day should be fine.

**Comment by JipSterk** [comment]
hi @uiii. first of all thanks for the pullrequest 💪🏻 I switched to mac about a year ago and was looking to transfer this repository to the [chocolatey](https://github.com/chocolatey-community) organisation. but couldn't wrap my head around it. I will set the job schedule to something more frequent like a day as you proposed (i was worried the build minutes of public/private was shared). the proposal to checkout the code and version the powershell scripts would seem nice. If you would try and implement it it would be great 👍🏻  also stay safe and stay sane ❤️  during these trying times

**Comment by uiii** [comment]
Ah, I understand, it is difficult to maintain a package you don't already use. Here is the update with commit https://github.com/JipSterk/Chocolatey-Packages/pull/2, so check it out. Thransferring the package to chocolatey organisation would not be easy if even possible as I quickly looked, because Unity doesn't serve the older versions of the hub, only the latest one. So it is not possible to make chocolatey package of older version, which is required by the community repo. Stay safe too 👍

**Pull request merged**
